# Generated by Django 5.0 on 2024-02-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_date_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctor',
            field=models.ManyToManyField(related_name='hospital', to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nurse',
            field=models.ManyToManyField(related_name='hospital', to='app.nurse'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='patient',
            field=models.ManyToManyField(related_name='hospital', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(related_name='patient', to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='app.nurse'),
        ),
    ]
